export const actions = {
  TOGGLE_ANSWER_FILTER: "TOGGLE_ANSWER_FILTER",
  CLEAR_FILTERS: "CLEAR_FILTERS",
  REQUEST_FORM: "REQUEST_FORM",
  REQUEST_FORM_SUCCESS: "REQUEST_FORM_SUCCESS"
};

export const filterTypes = {
  SINGLE_SELECT: "SINGLE_SELECT",
  MULTI_SELECT: "MULTI_SELECT",
  DATE_RANGE_SELECT: "DATE_RANGE_SELECT"
};

export const questionTypes = {
  CAMERA: "CAM",
  CHECKBOX: "CK",
  BAR_CODE: "CODE",
  DATE: "DATE",
  FREE_TEXT: "FT",
  IMAGE: "IMG",
  MULTIPLE_OPTION: "MO",
  NUMERIC: "NUM",
  SIGNATURE: "SIG",
  TITLE: "TI",
  YES_NO: "YN"
};
