export const actions = {
	TOGGLE_ANSWER_FILTER: 'TOGGLE_ANSWER_FILTER',
	CLEAR_FILTERS: 'CLEAR_FILTERS',
	REQUEST_FORM: 'REQUEST_FORM',
	REQUEST_FORM_SUCCESS: 'REQUEST_FORM_SUCCESS',
	TOGGLE_IS_LOADING: 'TOGGLE_IS_LOADING'
}

export const filterTypes = {
	SINGLE_SELECT: 'SINGLE_SELECT',
	MULTI_SELECT: 'MULTI_SELECT',
}